name: Update News (every 15m)

on:
  schedule:
    - cron: "*/15 * * * *"      # 00/15/30/45 分
    - cron: "7-59/15 * * * *"   # 07/22/37/52 分（兜底）
    - cron: "2,17,32,47 * * * *" # 02/17/32/47 分（再兜底）
  workflow_dispatch:            # 手动触发也可用

concurrency:
  group: "news-update"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run aggregator script
        run: python scripts/aggregator.py

      - name: Commit and push if changed
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"

          # 更新 .last_run 确保每次都有变更
          date +%s > .last_run

          git add news.json .last_run
          git commit -m "chore: auto update news" || echo "nothing to commit"
          git pull --rebase origin main || true
          git push || echo "push failed"
