name: Update News
on:
  schedule:
    - cron: "0 * * * *" # 每小时更新
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install feedparser
      - run: python scripts/aggregator.py
      - run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add news.json
          git commit -m "update news" || echo "no changes"
          git push

