name: Update News (every 15m)

on:
  schedule:
    - cron: "*/15 * * * *"      # 00/15/30/45（UTC）
    - cron: "7-59/15 * * * *"   # 07/22/37/52 兜底，减少 GitHub 定时抖动
  workflow_dispatch:

concurrency:
  group: "news-update"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install feedparser
      - run: python scripts/aggregator.py
      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          # 关键：提交 news.json + 心跳文件，确保每轮都有改动
          git add news.json .last_run
          git commit -m "chore: update news.json (auto)" || echo "no changes"
          git pull --rebase origin main || true
          git push || echo "push failed"
