name: Update News Feed

on:
  schedule:
    - cron: '*/30 * * * *'   # 每 30 分钟运行一次
  workflow_dispatch:         # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install feedparser

      - name: Run aggregator script
        run: python scripts/aggregator.py